### ISSUE TITLE
Do first release

### ISSUE THREAD

**Issue by carsongee** [mitodl/PyLmod#23]
Determine what we think the milestone is for a first release and then do so.

**Comment by pdpinch** [comment]
Two thoughts on a first release:

1. We need at least one method in the membership class. Since we moved the various get_students methods into the gradebook class, this will be new work. 
2. Since the membership class is a green field now, can we just have a very basic method that just passes requests through directly to the membership service? This would also simply our docs, since we can just point to the IS&T docs on the membership API.

**Comment by carsongee** [comment]
So talking with @pdpinch and realizing more and more about how these APIs are completely independent but heavily overlapping, I agree and propose we do one last refactor before release. The proposal:

- Refactor base url in the constructor to just be `http(s)://<domain-name>[:port]/`
- Refactor Membership to append `services/membership` in the constructor
- Refactor Gradebook to append `services/gradebook` to the constructor
- Drop `Client` entirely since this change will make it so `get`, `post`, and `delete` are unresolvably ambiguous
- Refactor `grades2stellar` to use `Gradebook` and truncate the default base url

This will give us a good release point since `Membership` will legitimately work with the `Base` methods and have some functioning code that differentiates it from `Gradeboo`k (i.e. the shortcut constructor append).

We could also add a trivial call like `get_staff` to membership as well.  That should be fairly quick and easy to write, but I don't think that should hold back the release neccessarily as long as we have a doc showing that as an example for how to use `Membership`

**Comment by Ferdi** [comment]
Good plan !

**Comment by pwilkins** [comment]
This sounds all good to me, especially adding the get_staff() function to nail down a pattern for new membership functions since the earliest implementation seems to win.

**Comment by carsongee** [comment]
I've made this a check list now, with completed work being checked off, feel free to tackle issues and mark more off (I think you can do that, if not tell me and I'll check them off)
