### ISSUE TITLE
ReadTheDocs can't resolve version number from distribution

### ISSUE THREAD

**Issue by pwilkins** [mitodl/PyLmod#25]
The value of version number is set in setup.py and put into `__version__` by `__init__.py`  This technique is DRY, and works locally but doesn't work on ReadTheDocs.  The simplest workaround is just hard-code the version number, but there may be a way to make it work as we want.

**Comment by pwilkins** [comment]
It turns out that the version number is getting set, but our test to verify this is not effective.

**Comment by carsongee** [comment]
Why do you say our test is not effective? This is still a bug somewhere in readthedocs that we haven't been able to reproduce, and the test is fine since the version is set properly on every machine we've tried it on (well at least the three I've used).  Can you produce where version returns the exception string?

**Comment by pwilkins** [comment]
Our code raises the exception.  Is that what you're asking?

**Comment by pwilkins** [comment]
Our test asserts that the path to the distribution as returned by the Distribution object's 'location' attribute is the same as the path to  __init__.py.  On ReadTheDocs it isn't so we raise the 'Distribution not found' exception

**Comment by carsongee** [comment]
I'm still not sure what you mean by test.  Our only unit test for version asserts it is a valid semantic version number (https://github.com/mitodl/PyLmod/blob/master/pylmod/tests/test_module.py#L17), but it sounds like you are referring to the actual code that seeks out the version.  I wouldn't consider that a test, it is using `pkgresources.getdistribution` to find out it's version from the environment and readthedocs environment isn't setting our version.  Where are you suggesting putting the version number, if in conf.py, that is fine with me to satisfy the weirdness that is readthedocs. I don't believe there is a different solution for __init__.py to have the version, see http://stackoverflow.com/questions/17583443/what-is-the-correct-way-to-share-package-version-with-setup-py-and-the-package for the discussion and accepted answer we are using.  I suppose we could do the _version.py file and read that file in, in setup.py, but it is less than ideal for what is just a really strange behavior that only occurs on readthedocs servers.

**Comment by pwilkins** [comment]
I used the wrong term when referring to the try/except block in `__init__.py`.  That was what I meant by "test".  So it isn't a test, per se.  

We are still talking about different things, though.  What I'm talking about is that we don't successfully set the value of `__version__` in  `__init__.py` even though the value is available through the Distribution object we retrieve.  Why do you say that RTD isn't setting the version?

**Comment by pwilkins** [comment]
I wish I had found that SO link you provided above.  That would have explained a lot.

**Comment by pwilkins** [comment]
Obviously I'm not going to improve upon those suggestions.  What do you recommend we do to fix this in our code?
