### ISSUE TITLE
Add Membership.get_staff() function

### ISSUE THREAD

**Issue by pwilkins** [mitodl/PyLmod#34]
It would be useful to retrieve staff members from LMod web service

**Comment by pwilkins** [comment]
There are multiple ways to retrieve staff members from LMod web service.  There is an endpoint to get staff for a gradebook, and an endpoint to get staff for a course.  I'm checking with the LMod team to determine if these lists are different.  I don't know if they have an invariant such that every gradebook has one course and one course has one gradebook.

**Comment by pwilkins** [comment]
@pdpinch @carsongee  What if we implemented a GradeBook.get_gradebook_staff() and a Membership.get_course_staff()?  (I still haven't heard back from the LMod team about whether they're the same list.)

**Comment by carsongee** [comment]
sounds good

**Comment by pwilkins** [comment]
As a result of our discussion, I will implement a get_staff() function in GradeBook and another one in Membership.  I'll create a PR for each.

**Comment by pwilkins** [comment]
This is the response to my question to the LMod team about multiple ways to retrieve staff:

> Good afternoon,
> Members come from a course's membership regardless of which service/scope the members are being pulled for (gradebook vs. course). To the best of our knowledge, the lists would always be the same.
> 
> Sincerely,
> Learning Modules Support*

In light of this response, I think we can skip the GradeBook.get_staff() implementation for MVP.  
@pdpinch @carsongee Please concur or reject.  :-)

**Comment by pdpinch** [comment]
Makes sense to me. 

Not sure how best to document this for users, but for Mvp my interests are very narrow. 

----------------
I am mobile.

**Comment by carsongee** [comment]
Sounds good, I would add a note either in the gradebook class doc string, or probably more simply in the https://github.com/mitodl/PyLmod/blob/master/docs/api.rst file under GradeBook to convey this.

**Comment by pwilkins** [comment]
@pdpinch @carsongee @bdero I have an API best practices question: If I am to faithfully map my Membership.get_staff() to the LMod web service API, I would pass get_staff() a course identifier.  The way to get a course identifier is to call GradeBook.get_options() with the gradebook identifier.  It appears that for our usage, using the Membership.get_staff() requires a GradeBook object.  

So the question is whether a good API has the user making multiple API calls, or hides multiple calls behind convenience API endpoints that reflect the usage we expect our users to want, even if these convenience APIs are contrary to the spirit of the underlying web service?
