### ISSUE TITLE
Refactor code into distinct Gradebook and Membership classes

### ISSUE THREAD

**Issue by pwilkins** [mitodl/PyLmod#7]
I intend to refactor the StellarGradebook class.  My goals are:
1. remove common code to a class named base.py
1. create gradebook.py and membership.py files for the calls made to each of these LMOD services
1. move code around as required

Is this what you had in mind for the refactoring PR? @pdpinch @carsongee

**Comment by pdpinch** [comment]
I think it would be useful to have an issue for gradebook.py and an issue for membership.py -- so we can discuss the functionality of each separately. 

Otherwise, this is exactly what I had in mind.

**Comment by pwilkins** [comment]
@pdpinch see issues #8 and #9
