### ISSUE TITLE
Refactoring: create Membership class

### ISSUE THREAD

**Issue by pwilkins** [mitodl/PyLmod#8]
Refactor StellarGradebook class into a Membership class
@pdpinch @carsongee

**Comment by pwilkins** [comment]
There was some question whether the current StellarGradebook class calls any membership service endpoints.   This is the endpoint called for get_students(): https://learning-modules-test.mit.edu/service/gradebook/students/...

**Comment by pwilkins** [comment]
There is no code from StellarGradebook that calls the Membership service.  I assumed that the names "Gradebook" and "Membership" refer to the two LMod services and that the names indicated that the API calls in each were to the named LMod service.  The other way to think of the class naming is to differentiate them by their conceptual distinction, i.e. get_students() would go in the Membership class since it conceptually answers a question about membership.

**Comment by carsongee** [comment]
I thought `get_students` and the related `get_student_by_email` would go in this class. Are the endpoints between the two different on the remote end?  If so, shouldn't they return the same data, and thus we could replace one call with the other to have the semantics match the backend? Do you have a link handy on the LMOD API docs that would distinguish?

**Comment by pwilkins** [comment]
https://learning-modules-test.mit.edu/service/gradebook/doc.html#Students
https://learning-modules-test.mit.edu/service/membership/doc.html#Membership

**Comment by pwilkins** [comment]
My reading of this is that Membership is about groups, not about students.  Students only exist in the context of a Gradebook.

**Comment by pwilkins** [comment]
The endpoints of get_students() and get_student_by_email() have the same endpoint in Ike's code even though the LMod service has a separate endpoint for each of these calls.

**Comment by carsongee** [comment]
But the students of a course are in a group which you get get the id of, and then list of the members in that group, so there is a point of redudancy here where you can get the same information from either API.  To me, semantically, it makes sense to have these in the Membership class, and if we want to be pure about the endpoints for a class, we can make an issue to swap out the current implementation with one that uses the membership API.

**Comment by pwilkins** [comment]
On your recommendation, I will put these two functions in the Membership class, though will continue to call the LMod Gradebook service for their data.
